--테이블 삭제
DROP TABLE Z_TEST_JOIN_DEPARTMENT;
DROP TABLE Z_TEST_JOIN_MEMBER;

--테이블 생성 (부서테이블)
CREATE TABLE Z_TEST_JOIN_DEPARTMENT(
DEPT_CODE VARCHAR2(100) NOT NULL PRIMARY KEY,
DEPT_NAME VARCHAR2(200) NOT NULL
);
COMMIT;

--테이블 생성 (학생테이블)
CREATE TABLE Z_TEST_JOIN_MEMBER(
ID VARCHAR2(100) NOT NULL PRIMARY KEY,
NAME VARCHAR(500) NOT NULL,
DEPT_CODE VARCHAR2(500) NOT NULL,
TEL VARCHAR2(500) NOT NULL
);
--부서정보 입력
INSERT INTO Z_TEST_JOIN_DEPARTMENT(DEPT_CODE, DEPT_NAME)
VALUES ('D001', '헬스케어경영학과');

INSERT INTO Z_TEST_JOIN_DEPARTMENT(DEPT_CODE, DEPT_NAME)
VALUES ('D002', '응용통계학과');

INSERT INTO Z_TEST_JOIN_DEPARTMENT(DEPT_CODE, DEPT_NAME)
VALUES ('D003', '유럽어문화학과');

INSERT INTO Z_TEST_JOIN_DEPARTMENT(DEPT_CODE, DEPT_NAME)
VALUES ('D004', '유아교육학과');

INSERT INTO Z_TEST_JOIN_DEPARTMENT(DEPT_CODE, DEPT_NAME)
VALUES ('D005', '기획부서');

INSERT INTO Z_TEST_JOIN_DEPARTMENT(DEPT_CODE, DEPT_NAME)
VALUES ('D006', '의료경영학과');

--부서 정보 조회
SELECT * FROM Z_TEST_JOIN_DEPARTMENT;

--학생 데이터 입력
INSERT INTO Z_TEST_JOIN_MEMBER(ID,NAME,DEPT_CODE,TEL)
VALUES ('S001','김일영','D001','01012345678');

INSERT INTO Z_TEST_JOIN_MEMBER(ID,NAME,DEPT_CODE,TEL)
VALUES ('S002','김일일','D002','01012345678');

INSERT INTO Z_TEST_JOIN_MEMBER(ID,NAME,DEPT_CODE,TEL)
VALUES ('S003','김일이','D003','01012345678');

INSERT INTO Z_TEST_JOIN_MEMBER(ID,NAME,DEPT_CODE,TEL)
VALUES ('S004','김일삼','D004','01012345678');

INSERT INTO Z_TEST_JOIN_MEMBER(ID,NAME,DEPT_CODE,TEL)
VALUES ('S005','김일사','D004','01012345678');

INSERT INTO Z_TEST_JOIN_MEMBER(ID,NAME,DEPT_CODE,TEL)
VALUES ('S006','김일오','D007','01012345678');

--학생정보 조회
SELECT * FROM Z_TEST_JOIN_MEMBER;

--INNER JOIN 
SELECT * 
FROM Z_TEST_JOIN_MEMBER A INNER JOIN Z_TEST_JOIN_DEPARTMENT B
ON A.DEPT_CODE = B.DEPT_CODE;

--JOIN 
SELECT * 
FROM Z_TEST_JOIN_MEMBER A JOIN Z_TEST_JOIN_DEPARTMENT B
ON A.DEPT_CODE = B.DEPT_CODE;

--OUTER JOIN 
SELECT * 
FROM Z_TEST_JOIN_MEMBER A FULL OUTER JOIN Z_TEST_JOIN_DEPARTMENT B
ON A.DEPT_CODE = B.DEPT_CODE;

--LEFT JOIN 
SELECT * 
FROM Z_TEST_JOIN_MEMBER A LEFT JOIN Z_TEST_JOIN_DEPARTMENT B
ON A.DEPT_CODE = B.DEPT_CODE;

--RIGHT JOIN 
SELECT * 
FROM Z_TEST_JOIN_MEMBER A RIGHT JOIN Z_TEST_JOIN_DEPARTMENT B
ON A.DEPT_CODE = B.DEPT_CODE;

